Check boxes next to the years that you want to select.<br>
  <input type="checkbox" name="yearlist[]" value="2013" checked>2013 -- most recent completed year</input><br>
  <input type="checkbox" name="yearlist[]" value="2012">2012</input><br>
  <input type="checkbox" name="yearlist[]" value="2011">2011</input><br>
  <input type="checkbox" name="yearlist[]" value="2010">2010</input><br>
  <input type="checkbox" name="yearlist[]" value="2009">2009</input><br>
  <input type="checkbox" name="yearlist[]" value="2008">2008</input><br>
