<?php

global $carryoverfromonemonth;
$carryoverfromonemonth=false;

global $externalQueryCount;
$externalQueryCount = 0;

global $weightedExternalQueryCount;
$weightedExternalQueryCount = 0;

global $unavailableCount;
$unavailableCount = 0;

global $pagespecificationerror;
$pagespecificationerror = false;

global $monthspecificationerror;
$monthspecificationerror = false;

global $yearspecificationerror;
$yearspecificationerror = false;
?>
