<tr><td>Enter the language Wikipedia that you are interested in: </td><td><select name="language">
  <option value="en">English (en)</option>
  <option value="de">German (Deutsch) (de)</option>
  <option value="fr">French (Francais) (fr)</option>
  <option value="es">Espanol (Spanish) (es)</option>
  <option value="it">Italian (Italiano) (it)</option>
  <option value="nl">Dutch (Nederlands) (nl)</option>
  <option value="pl">Polish (Polski) (pl)</option>
  <option value="ru">Russian (Russkiy) (ru)</option>
  <option value="pt">Portuguese (Portugues) (pt)</option>
  <option value="sv">Swedish (Svenska) (sv)</option>
  <option value="zh">Chinese (Zhongwen) (zh)</option>
  <option value="simple">Simple English Wikipedia (simple)</option>
  <option value="zh-classical">Chinese (Zhongwen) (classical) (zh-classical)</option>
  <option value="no">Norwegian (Norsk (bokmal)) (no)</option>
  <option value="fi">Finnish (fi)</option>
  <option value="hi">Hindi (hi)</option>
</select></td></tr>
